services:
  backend:
    container_name: cafedodo-backend
    depends_on:
      - dind
    build:
      dockerfile: Dockerfile
    volumes:
      - docker-cert:/cert
    environment:
      - DOCKER_CERT_PATH=/cert/client
      - DOCKER_TLS_VERIFY=true
    ports:
      - 6969:6969
    restart: "unless-stopped"
    networks:
      - cafedodo-net


  dind:
    image: docker:dind
    container_name: cafedodo-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: "unless-stopped"
    volumes:
      - docker-cert:/certs
    networks:
      - cafedodo-net

volumes:
  docker-cert:

networks:
  cafedodo-net:
    driver: bridge

