version: '3'

services:
  backend:
    container_name: cafedodo-backend
    depends_on:
      - dind
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - docker-cert:/cert
    environment:
      - DOCKER_CERT_PATH=/cert/client
      - DOCKER_TLS_VERIFY=true
    ports:
      - 6969:6969
    restart: "unless-stopped"

  dind:
    image: docker:dind
    container_name: cafedodo-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: "unless-stopped"
    volumes:
      - docker-cert:/certs
      - ./data/docker:/var/lib/docker
      - ./data/:/app/data/

volumes:
  docker-cert:

