FROM golang

WORKDIR /root

COPY ./backend/go.mod ./backend/go.sum ./backend/
RUN go mod -C backend download

COPY ./backend ./backend
RUN go build -C backend -ldflags "-s -w" -o out/main

COPY ./image ./image

EXPOSE 6969/tcp

ENTRYPOINT ["./backend/out/main", "-i", "./image", "-k", "/apikey/key.txt", "-f", "/devenvs", "-t", "/devenvs-tmp"]

