FROM node:alpine

WORKDIR /root

COPY ./frontend/package.json ./frontend/package-lock.json ./frontend/
RUN npm install --prefix frontend

COPY ./frontend ./frontend
RUN npm run --prefix frontend build

EXPOSE 3000/tcp

ENTRYPOINT ["npm", "run", "--prefix", "frontend", "start"]

