version: '3'

services:
  frontend:
    container_name: replme-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: "unless-stopped"

  backend:
    container_name: replme-backend
    depends_on:
      - dind
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - docker-cert:/cert
      - replme-data:/data
      - devenvs-tmp:/devenvs
    environment:
      - DOCKER_CERT_PATH=/cert/client
      - DOCKER_TLS_VERIFY=true
      - GIN_MODE=release
      - REPL_LOG=debug
      - REPL_IMG_TAG=ptwhy
      - REPL_SQLITE=/data/replme.db
      - REPL_API_KEY=/data/apikey
      - REPL_DEVENVS=/data/devenvs
      - REPL_DEVENVS_TMP=/devenvs
      - REPL_CONTAINER_LOGS=/data/logs
    restart: "unless-stopped"

  fix-certs-perms:
    image: alpine:latest
    command: chown 1000:1000 -R /certs
    volumes:
      - docker-cert:/certs

  dind:
    image: docker:dind-rootless
    container_name: replme-dind
    depends_on:
      - fix-certs-perms
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: "unless-stopped"
    # logging:
    #   driver: none
    ulimits:
      nproc: 79830
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - docker-cert:/certs
      - docker-data:/var/lib/docker
      - docker-app-data:/app/data/
      - devenvs-tmp:/devenvs

  nginx:
    container_name: replme-nginx
    depends_on:
      - backend
      - frontend
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/replme.conf
    ports:
      - 6969:6969
    restart: "unless-stopped"


volumes:
  replme-data:
  devenvs-tmp:
  docker-cert:
  docker-data:
  docker-app-data:

