version: '3'

services:
  replme-checker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 16969:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=replme-mongo
      - MONGO_PORT=27017
      - MONGO_USER=replme_checker
      - MONGO_PASSWORD=replme_checker

  replme-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: replme_checker
      MONGO_INITDB_ROOT_PASSWORD: replme_checker
