version: '3'

services:
  replme-checker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 16969:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=replme-mongo
      - MONGO_PORT=27017
      - MONGO_USER=replme_checker
      - MONGO_PASSWORD=replme_checker

  replme-mongo:
    image: mongo@sha256:54996a559c724c726a31fb8131e1c9088a05f7e531760e2897212389bbf20fed
    volumes:
      - checker-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: replme_checker
      MONGO_INITDB_ROOT_PASSWORD: replme_checker

volumes:
  checker-db:
