services:
  cafedodo-checker:
    build:
      dockerfile: Dockerfile
    ports:
      - 16969:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=cafedodo-mongo
      - MONGO_PORT=27017
      - MONGO_USER=cafedodo_checker
      - MONGO_PASSWORD=cafedodo_checker
    networks:
      - service_cafedodo-net

  cafedodo-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cafedodo_checker
      MONGO_INITDB_ROOT_PASSWORD: cafedodo_checker
    networks:
      - service_cafedodo-net

  cafedodo-crc32:
    build:
      dockerfile: Dockerfile.crc32
    networks:
      - service_cafedodo-net

networks:
  service_cafedodo-net:
    external: True 

